"""Configurable, punctuation-tolerant aliases for workbook fields."""

COLUMN_ALIASES: dict[str, list[str]] = {
    "date": ["date", "sales date", "bill date", "invoice date", "transaction date"],
    "time": ["time", "bill time", "transaction time"],
    "store": ["store", "store name", "location", "branch", "outlet"],
    "section": ["section", "store section"],
    "department": ["department", "dept", "department name"],
    "division": ["division", "business division"],
    "category": ["category", "product category"],
    "subcategory": ["subcategory", "sub category"],
    "brand": ["brand", "brand name"],
    "product": ["product", "product name", "item", "item name", "description"],
    "sku": ["sku", "item code", "product code", "barcode"],
    "quantity": [
        "quantity",
        "qty",
        "units",
        "sales quantity",
        "bill quantity",
        "sum of bill quantity",
    ],
    "gross_sales": ["gross sales", "gross amount", "mrp value", "gross revenue"],
    "net_sales": ["net sales", "net amount", "sales amount", "revenue", "sale"],
    "discount": ["discount", "discount amount", "promo discount"],
    "cost": ["cost", "cogs", "cost of goods sold", "purchase cost"],
    "target": ["target", "sale target", "sales target", "budget"],
    "footfall": ["footfall", "visitors", "customer count"],
    "transaction_id": ["bill no", "invoice no", "transaction id", "receipt no"],
    "nob": ["nob", "number of bills", "bill count", "transaction count"],
    "atv": ["atv", "average transaction value"],
    "rpv": ["rpv", "revenue per visitor"],
    "conversion": ["conversion percentage", "conversion percent", "conversion"],
    "achievement": ["achievement percentage", "achievement percent", "achievement"],
    "basket_size": ["bucket size", "basket size"],
}
